### ISSUE TITLE
filter out zero-sized devices by looking at "size" attribute in sysfs to avoid "no medium found" errors

### ISSUE THREAD

**Issue by miquecg** [lvmteam/lvm2#13]
Not sure if this is an issue or an expected behaviour, so let's ask.

```
➜ # ~  pvscan --cache
  /dev/sdd: open failed
  /dev/sde: open failed
  /dev/sdf: open failed
  /dev/sdg: open failed
➜ # ~  pvscan
  /dev/sdd: open failed
  /dev/sde: open failed
  /dev/sdf: open failed
  /dev/sdg: open failed
  PV /dev/mapper/ssd         VG ssd             lvm2 [<118,74 GiB / <108,74 GiB free]
  PV /dev/sdb1               VG storage         lvm2 [<931,51 GiB / 0    free]
  PV /dev/mapper/crypt_hdd   VG hdd             lvm2 [<465,76 GiB / <73,76 GiB free]
  Total: 3 [1,48 TiB] / in use: 3 [1,48 TiB] / in no VG: 0 [0   ]
```

If I run pvscan without `--cache` and `use_lvmetad` option is enabled in configuration, I'd expect second command from the example to not scan devices again, which looks like it's happening.

Also, but not strictly related, is it normal that `lvm2-pvscan@.service` unit in systemd runs without cache at boot? For some reason I started to see `... open failed` messages during boot process.

This is for lvm2 2.02.183 version on Arch Linux.

Thanks!

**Comment by teigland** [comment]
The errors are produced when device nodes exist for devices that don't exist on the system.  It's udev's job to create and remove device nodes at the right time, so maybe there's something odd happening with udev.

To check if a command is actually reading a device you would need to run it with -vvvv and look at the debugging.  (The open error could occur when lvm tries to open the device to check its size, for example, not necessarily to read it.)

The lvm2-pvscan service should be running pvscan --cache <device>

**Comment by prajnoha** [comment]
> If I run pvscan without `--cache` and `use_lvmetad` option is enabled in configuration, I'd expect second command from the example to not scan devices again, which looks like it's happening.
> 

The `open` here probably comes from the device filters inside LVM. If using lvmetad, we shouldn't need to execute certain filters anymore: devices which are already cached in lvmetad passed these filters, but I need to check the code and recall... It's possible something got changed there recently or there's a filter we still need to execute for some reason (...and hence open the device to scan for certain signatures on disk to apply the filter based on that).

> Also, but not strictly related, is it normal that `lvm2-pvscan@.service` unit in systemd runs without cache at boot? For some reason I started to see `... open failed` messages during boot process.
> 

Normally, the `pvscan --cache <major>:<minor>` scans only the `<major>:<minor>` device for LVM metadata. However, if this is the very first LVM command that sees lvmetad empty, such command initiates full scan so it can fill up lvmetad with any metadata from devices which had already been present on the system before lvmetad actually started (that happens at boot usually or after lvmetad has been restarted). And usually, the very first LVM command to see lvmetad empty is the `pvscan --cache <major>:<minor>` command executed from within `lvm2-pvscan@<major>:<minor>.service`.

**Comment by prajnoha** [comment]
> The errors are produced when device nodes exist for devices that don't exist on the system. It's udev's job to create and remove device nodes at the right time, so maybe there's something odd happening with udev.

Actually, if it's `/dev/<kernel_device_name>` and /dev/sd* are kernel device names, the nodes are created directly by kernel through `devtmpfs` - so the node is created under `/dev` as soon as there's kernel representation (and vice versa when the device is removed from kernel). So the failure to open the device must have a different reason... I'm thinking of permissions, but I think that would be logged directly that it's because of perms, so some other problem with the device probably.

Is there anything logged in dmesg/systemd journal about those devices?

**Comment by prajnoha** [comment]
> > If I run pvscan without `--cache` and `use_lvmetad` option is enabled in configuration, I'd expect second command from the example to not scan devices again, which looks like it's happening.
> 
> The `open` here probably comes from the device filters inside LVM. If using lvmetad, we shouldn't need to execute certain filters anymore: devices which are already cached in lvmetad passed these filters, but I need to check the code and recall...

...so, yes, these `open` calls come from device filtering inside LVM and it's expected here for pvscan (as well as pvs -a and probably others where we need to process all devices).

There's some more info about this in this commit:
https://github.com/lvmteam/lvm2/commit/e0ce7285794da030a3e87d9b0a81217d6155c3bc

Back to the report:

  - the `open` calls are expected here for pvscan even after we filled lvmetad with results from previous `pvscan --cache` call

  - the failed `open` calls - let's see that dmesg/systemd journal whether it has logged any problem with that device (so this is then probably not an LVM issue, but issue with disk access and availability)

**Comment by miquecg** [comment]
> * the failed `open` calls - let's see that dmesg/systemd journal whether it has logged any problem with that device (so this is then probably not an LVM issue, but issue with disk access and availability)

You're right @prajnoha.

I've run `pvscan -vvvv` as @teigland suggested and I've found these lines:

```
#device/dev-cache.c:1212          Creating list of system devices.
#device/dev-cache.c:723           Found dev 8:48 /dev/sdd - new.
#device/dev-cache.c:763           Found dev 8:48 /dev/disk/by-id/usb-Generic-_Compact_Flash_20070818000000000-0:0 - new alias.
#device/dev-cache.c:763           Found dev 8:48 /dev/disk/by-path/pci-0000:00:1a.0-usb-0:1.3:1.1-scsi-0:0:0:0 - new alias.
#device/dev-cache.c:723           Found dev 8:64 /dev/sde - new.
#device/dev-cache.c:763           Found dev 8:64 /dev/disk/by-id/usb-Generic-_SM_xD-Picture_20070818000000000-0:1 - new alias.
#device/dev-cache.c:763           Found dev 8:64 /dev/disk/by-path/pci-0000:00:1a.0-usb-0:1.3:1.1-scsi-0:0:0:1 - new alias.
#device/dev-cache.c:723           Found dev 8:80 /dev/sdf - new.
#device/dev-cache.c:763           Found dev 8:80 /dev/disk/by-id/usb-Generic-_SD_MMC_20070818000000000-0:2 - new alias.
#device/dev-cache.c:763           Found dev 8:80 /dev/disk/by-path/pci-0000:00:1a.0-usb-0:1.3:1.1-scsi-0:0:0:2 - new alias.
#device/dev-cache.c:723           Found dev 8:96 /dev/sdg - new.
#device/dev-cache.c:763           Found dev 8:96 /dev/disk/by-id/usb-Generic-_MS_MS-Pro_20070818000000000-0:3 - new alias.
#device/dev-cache.c:763           Found dev 8:96 /dev/disk/by-path/pci-0000:00:1a.0-usb-0:1.3:1.1-scsi-0:0:0:3 - new alias.
```

This is caused by a multicard reader I have plugged in. If I try to read from any empty slot I do have errors `media not found`.

Do you want me to share the complete output of the command for completeness?

**Comment by prajnoha** [comment]
Yes, that's it - the card... If you remove the card, there's still a device representation present on the system and we end up with "no media found" error (...the same would happen for CD/DVD/BD drives after removing the media). So this is all expected then.

I got a bit mislead by the error message that was without the reason given:
```
   /dev/sdd: open failed
```

I'd expect that to be:
```
  /dev/sdd: open failed: No medium found
```

Anyway,  we know now...

We do have an internal filter to filter out devices which do not have enough size to hold a PV. Thing is, that for this filter to work, we need to open the device and run `BLKGETSIZE64` ioctl. Of course, if that device is not backed by any media, we can't open that at all - so that's the error reported then.

We could possibly improve this by looking at `size` attribute in `sysffs` first, e.g. on my system where `sda` is the removed card:

```
  # cat /sys/block/sdd/size
  0
```

And we could make this a part of the `usable` internal LVM filter, relevant parts of the code are here (...actually, we already do this when `external_device_info_source="udev"` is set in `lvm.conf`):

https://github.com/lvmteam/lvm2/blob/420af27f088a3808816ba3ab5b47dfa400fef308/lib/filters/filter-usable.c#L108-L164

https://github.com/lvmteam/lvm2/blob/420af27f088a3808816ba3ab5b47dfa400fef308/lib/filters/filter-usable.c#L94-L106

I'll think about adding this...

**Comment by miquecg** [comment]
Cool. Many thanks for helping me to understand this. It's not big deal but a bit misleading because I totally forgot about that card reader hehe.
