### ISSUE TITLE
what is the benefit for using aio in bcache?

### ISSUE THREAD

**Issue by wangwang3210** [lvmteam/lvm2#20]
In my environment
1. when I use aio engine created by create_async_io_engine()
# time lvs
real	0m0.093s
user	0m0.017s
sys	0m0.009s

2. when I close aio engine by setting use_aio=0 in /etc/lvm/lvm.conf
# time lvs
real	0m0.026s
user	0m0.007s
sys	0m0.019s

I wonder why adding aio feature to lvm? It takes much time when call io_setup io_destroy. Actually， it doesn't make scanning faster.
Thanks

**Comment by zkabelac** [comment]
Hi

You need to compare with different number of devices.  If you have very low number of devices that are very fast (i.e. nearly zero latency NVMe)  - there will be close to 0 benefit of aio (or even it may get slightly slower due to extra expensive syscalls).

But once you start to work with hundreds of disks which also do have some seek time - there should be measurable improvement of scanning time.

If there is not - that there is bug  somewhere in code  - i.e. some regression - adding extra reads...  in all case it would be then worth to report as bug -  be sure to provide reproducible test and trace (-vvvv) with timestamps in this case then.
