### ISSUE TITLE
libdevmapper: Unlink the symlinks under `/dev/mapper` before destroying a device

### ISSUE THREAD

**Issue by DemiMarie** [lvmteam/lvm2#66]
Before destroying a device-mapper device, libdevmapper should delete the symlink for that device under `/dev/mapper`.  This avoids race conditions by ensuring that opening `/dev/mapper/somedevice` always returns the correct device if it succeeds, even if the major and minor number of the block device are later reused.  Relying on udev for this is racy, since udev will not delete the symlink until after the device has been destroyed.

**Comment by zkabelac** [comment]
lvm2 has nothing to do (nowadays)  with content of  /dev  directory.   It's fully managed by udev.
When device is 'destroyed'  - the event is processed first by kernel (so  /dev/dm-XXX is removed) and later processed by userspace chain with its udev rules - and at this point any symlinks are being removed.

And yes - relying on udev  *IS* racy by design - user needs to use other synchronization methods - aka in term of  Lvm2 usage - open devices after they are activated  and  do not try to access them before you deactivate them (you cannot deactivate device in use).

Close as this is currently compliant with existing design.
