### ISSUE TITLE
libboost required?!

### ISSUE THREAD

**Issue by egberts** [lvmteam/lvm2#87]
Over here at embedded Linux building, the latest LVM2 requires `libboost`?!

So I noticed that I could stop using `libboost` by a link flag to exclude the library but....

Ummmmm, we did not require the use of boost include file before the LVM team introduced `thin` provisioning, right?

If so, can we break away from boost include files (as well as the `libboost.so`) if THIN were disabled by compiler flag?

# Rationale
Primary reason is that `libboost` is a beast on limited storage space (as well as a beast during compiling and linking).

**Comment by zkabelac** [comment]
Dne 22. 07. 22 v 16:10 Egbert napsal(a):
> Over here at embedded Linux building the latest LVM2 requires |libboost|?!
> 
> So I noticed that I could stop using |libboost| by a compiler flag but....
> 
> Ummmmm, we did require the use of boost include before introducing |thin| 
> provisioning, right?
> 
> If so, can we break away from libboost and its mandatory development include 
> header files of libboost if THIN were disabled?

lvm2 is not using libboost.

devicemapper persistent data package (containing tools like cache_check, 
thin_check...) does use this C++ library (for now - it's going to be soon 
released as 'Rust' package.

So not sure what you are building or trying to use - but I'm pretty sure lvm2 
itself does NOT use any C++ library for anything.

Although if you want to use  thin/cache... you likely should use d-m-p-d 
packages or otherwise you might end with unrecoverable situations....
(As lvm2 calls these tools via 'exec').

Regards

Zdenek
