### ISSUE TITLE
lvm2_run side effect: umask set in _process_config() is not restored back

### ISSUE THREAD

**Issue by gwendalcr** [lvmteam/lvm2#99]
When lvm2_run() is called directly from an external program , _process_config() - through  lvm2_init(), cmdlib_lvm2_init(), init_lvm() , create_toolcontext() - is setting the umask to a proper value (default 0077), but is never restored.

Either lvm2_run() or lvm_init()/lvm_exit() should take care of it, or the documentation updated to indicate umask() as to be called before and after calling lvm2_run().

**Comment by zkabelac** [comment]
lvm2_run is purely internal  API - there is *NO* public supported  API from lvm2 side.
The only supported use of lvm2 is though call of lvm2 command!!

We are incapable to support any library usage of lvm2  (it'd be seriously complicated)

So if anyone is using  'lvm2_run()' from external program - it needs to stop doing so - and needs to switch to fork of lvm2 command.

Closing this issue   - since it is misuse from user side.
